package Struct

type Database struct {
	Host            string `json:"host"`
	Version         string `json:"version"`
	Postgres_engine string `json:"postgres_engine"`
	Release_channel string `json:"release_channel"`
}

type Project struct {
	Id                string   `json:"id"`
	Ref               string   `json:"ref"`
	Organization_id   string   `json:"organization_id"`
	Organization_slug string   `json:"organization_slug"`
	Name              string   `json:"name"`
	Region            string   `json:"region"`
	Status            string   `json:"status"`
	Database          Database `json:"database"`
	Created_at        string   `json:"created_at"`
}

type Analytics struct {
	Timestamp           string  `json:"timestamp"`
	Total_auth_requests int  `json:"total_auth_requests"`
	Total_realtime_requests int  `json:"total_realtime_requests"`
	Total_rest_requests int  `json:"total_rest_requests"`
	Total_storage_requests int  `json:"total_storage_requests"`
}

type Logs struct {
	Result []AutoGenerated `json:"result"`
	Error any `json:"error"`
}


type AutoGenerated struct {
	EventMessage string `json:"event_message"`
	ID           string `json:"id"`
	Metadata     []struct {
		LoadBalancerExperimentalRouting any   `json:"load_balancer_experimental_routing"`
		LoadBalancerGeoAwareInfo        []any `json:"load_balancer_geo_aware_info"`
		LoadBalancerRedirectIdentifier  any   `json:"load_balancer_redirect_identifier"`
		LogflareWorker                  []any `json:"logflare_worker"`
		Request                         []struct {
			Cf []struct {
				AsOrganization string `json:"asOrganization"`
				Asn            any    `json:"asn"`
				BotManagement  []struct {
					CorporateProxy any    `json:"corporateProxy"`
					DetectionIds   []any  `json:"detectionIds"`
					Ja3Hash        string `json:"ja3Hash"`
					Ja4            string `json:"ja4"`
					Ja4Signals     []any  `json:"ja4Signals"`
					JsDetection    []any  `json:"jsDetection"`
					Score          any    `json:"score"`
					StaticResource any    `json:"staticResource"`
					VerifiedBot    any    `json:"verifiedBot"`
				} `json:"botManagement"`
				City                       string `json:"city"`
				ClientAcceptEncoding       any    `json:"clientAcceptEncoding"`
				ClientTCPRtt               any    `json:"clientTcpRtt"`
				ClientTrustScore           int    `json:"clientTrustScore"`
				Colo                       string `json:"colo"`
				Continent                  any    `json:"continent"`
				Country                    string `json:"country"`
				EdgeRequestKeepAliveStatus any    `json:"edgeRequestKeepAliveStatus"`
				HTTPProtocol               string `json:"httpProtocol"`
				IsEUCountry                any    `json:"isEUCountry"`
				Latitude                   any    `json:"latitude"`
				Longitude                  any    `json:"longitude"`
				MetroCode                  any    `json:"metroCode"`
				PostalCode                 string `json:"postalCode"`
				Region                     any    `json:"region"`
				RegionCode                 any    `json:"regionCode"`
				RequestPriority            any    `json:"requestPriority"`
				Timezone                   string `json:"timezone"`
				TLSCipher                  any    `json:"tlsCipher"`
				TLSClientAuth              []any  `json:"tlsClientAuth"`
				TLSClientCiphersSha1       any    `json:"tlsClientCiphersSha1"`
				TLSClientExtensionsSha1    any    `json:"tlsClientExtensionsSha1"`
				TLSClientExtensionsSha1Le  any    `json:"tlsClientExtensionsSha1Le"`
				TLSClientHelloLength       any    `json:"tlsClientHelloLength"`
				TLSClientRandom            any    `json:"tlsClientRandom"`
				TLSExportedAuthenticator   []any  `json:"tlsExportedAuthenticator"`
				TLSVersion                 any    `json:"tlsVersion"`
				VerifiedBotCategory        any    `json:"verifiedBotCategory"`
			} `json:"cf"`
			Headers []struct {
				Accept               string `json:"accept"`
				CfCacheStatus        any    `json:"cf_cache_status"`
				CfConnectingIP       string `json:"cf_connecting_ip"`
				CfIpcountry          string `json:"cf_ipcountry"`
				CfRay                string `json:"cf_ray"`
				ContentLength        string `json:"content_length"`
				ContentLocation      any    `json:"content_location"`
				ContentRange         any    `json:"content_range"`
				ContentType          string `json:"content_type"`
				Date                 any    `json:"date"`
				Host                 string `json:"host"`
				Prefer               any    `json:"prefer"`
				Range                any    `json:"range"`
				Referer              any    `json:"referer"`
				SbForwardedFor       any    `json:"sb_forwarded_for"`
				SbGatewayMode        any    `json:"sb_gateway_mode"`
				SbGatewayVersion     any    `json:"sb_gateway_version"`
				Traceparent          string `json:"traceparent"`
				TransferEncoding     any    `json:"transfer_encoding"`
				UserAgent            string `json:"user_agent"`
				XAmzContentSha256    any    `json:"x_amz_content_sha256"`
				XAmzDate             any    `json:"x_amz_date"`
				XClientInfo          any    `json:"x_client_info"`
				XForwardedFor        any    `json:"x_forwarded_for"`
				XForwardedHost       any    `json:"x_forwarded_host"`
				XForwardedProto      string `json:"x_forwarded_proto"`
				XForwardedUserAgent  any    `json:"x_forwarded_user_agent"`
				XKongProxyLatency    any    `json:"x_kong_proxy_latency"`
				XKongUpstreamLatency any    `json:"x_kong_upstream_latency"`
				XRealIP              string `json:"x_real_ip"`
			} `json:"headers"`
			Host     string `json:"host"`
			Method   string `json:"method"`
			Path     string `json:"path"`
			Port     any    `json:"port"`
			Protocol string `json:"protocol"`
			Sb       []struct {
				Apikey   []any `json:"apikey"`
				AuthUser any   `json:"auth_user"`
				AwsV4    []any `json:"aws_v4"`
				Jwt      []struct {
					Apikey []struct {
						Invalid any `json:"invalid"`
						Payload []struct {
							Algorithm       string `json:"algorithm"`
							ExpiresAt       int    `json:"expires_at"`
							IssuedAt        int    `json:"issued_at"`
							Issuer          string `json:"issuer"`
							KeyID           any    `json:"key_id"`
							Role            string `json:"role"`
							SessionID       any    `json:"session_id"`
							SignaturePrefix string `json:"signature_prefix"`
							Subject         any    `json:"subject"`
						} `json:"payload"`
					} `json:"apikey"`
					Authorization []struct {
						Invalid any `json:"invalid"`
						Payload []struct {
							Algorithm       string `json:"algorithm"`
							ExpiresAt       int    `json:"expires_at"`
							IssuedAt        int    `json:"issued_at"`
							Issuer          string `json:"issuer"`
							KeyID           any    `json:"key_id"`
							Role            string `json:"role"`
							SessionID       any    `json:"session_id"`
							SignaturePrefix string `json:"signature_prefix"`
							Subject         any    `json:"subject"`
						} `json:"payload"`
					} `json:"authorization"`
				} `json:"jwt"`
			} `json:"sb"`
			Search any    `json:"search"`
			URL    string `json:"url"`
		} `json:"request"`
		Response []struct {
			Headers []struct {
				CfCacheStatus        string `json:"cf_cache_status"`
				CfRay                string `json:"cf_ray"`
				ContentLength        string `json:"content_length"`
				ContentLocation      any    `json:"content_location"`
				ContentRange         any    `json:"content_range"`
				ContentType          string `json:"content_type"`
				Date                 string `json:"date"`
				ProxyStatus          any    `json:"proxy_status"`
				SbErrorCode          any    `json:"sb_error_code"`
				SbGatewayMode        any    `json:"sb_gateway_mode"`
				SbGatewayVersion     string `json:"sb_gateway_version"`
				SbRequestID          any    `json:"sb_request_id"`
				ServerTiming         any    `json:"server_timing"`
				TransferEncoding     any    `json:"transfer_encoding"`
				XKongProxyLatency    any    `json:"x_kong_proxy_latency"`
				XKongUpstreamLatency any    `json:"x_kong_upstream_latency"`
				XSbErrorCode         any    `json:"x_sb_error_code"`
			} `json:"headers"`
			OriginTime int `json:"origin_time"`
			StatusCode int `json:"status_code"`
		} `json:"response"`
	} `json:"metadata"`
	Timestamp int64 `json:"timestamp"`
}

type Pause struct {
	Message string 
}
type Start struct {
    Message string `json:"message"`
}